### ISSUE TITLE
Tournaments TODO list

### ISSUE THREAD

**Issue by veloce** [veloce/lichobile#283]
- [x] variant icon in tournament header
- [x] mini board for featured game
- [x] podium
- [x] filter tournaments with supported variants
- [x] add ranking progress in leaderboard
- [x] add tournament player detail page (clickable from leaderboard)
- [x] implement possibility to play tournament
- [ ] tournament chat room
- [ ] tablet enhanced view
- [x] timeline entries
- [x] player rank in game screen 
- [x] remove chat during game
- [x] tournament countdown in game screen
- [x] berserk mode
- [ ] what about private tournaments?
- [x] browsable leaderboard

**Playable tournaments**
- [x] socket communication
- [x] return to tournament from round
- [x] tournament help page

**Player detail page**
- [x] scores sheet
- [x] stats
- [x] games list

**Comment by veloce** [comment]
@freefal thank you very much for your first PR. You laid the first foundation, now here is the roadmap to finish properly the feature!

We don't have to do it all before a first release. I think that make them playable is a requirement though. I don't know if it's hard to do now we have already the 'view' code. I'm willing to help you.

Then feel free to send any PR concerning all the points listed above :) Now I'm working on analysis and there is a lot of work to do, so I won't touch tournament for now, that's why you can pick any of them if you want to!

**Comment by veloce** [comment]
I'm not sure of what is to be done for playable tournaments, so the todo list is to be completed.

**Comment by JoelMon** [comment]
@freefal, was it difficult? haha :)

**Comment by freefal** [comment]
@veloce Ok, I have implemented:
1) "variant icon in tournament header"
2) "filter tournaments with supported variants" - I'm preventing people from joining crazyhouse tournaments, but letting them watch standings and games. Is there more to do here?
3) "add ranking progress in leaderboard"
4) "implement possibility to play tournament" - I didn't implement the "tournament help page"

To your list, I would add "Add a real podium for completed tournaments instead of just adding trophies to the leaderboard". I initially took the latter approach to save space, but the more I look at it, the more I dislike it.

I think that it is releasable at this stage, but defer to you.
I'll send you a PR tonight.

**Comment by freefal** [comment]
@veloce I just sent you a PR with the featured game mini board and the podium.

**Comment by freefal** [comment]
Next features on my list are chat and to make the leaderboard scrollable (flip through pages)
Don't think it matters whether they make it into the initial release of tournaments or not.

**Comment by veloce** [comment]
yep we can release without them. the only blocker to me is help page, which I'll do, and test the feature of course!

**Comment by freefal** [comment]
Should we close this issue?

**Comment by ornicar** [comment]
totally.
